<a href="https://colab.research.google.com/github/Akanksha131313/AI_Projects_Journey/blob/main/Word_Embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Word Embedding Techniques using Embedding Layer in Keras -**

In [47]:
### Libraries USed Tensorflow> 2.0  and keras
!pip install Tensorflow

In [48]:
import tensorflow as tf
print(tf.__version__)

2.19.0


###**One-hot Encoding ->**

In [49]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [50]:
### sentences
sent=[ 'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [51]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [52]:
### Vocabulary size
voc_size=500

### **One Hot Representation -**

In [53]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[107, 121, 454, 406], [107, 121, 454, 414], [107, 306, 454, 153], [398, 241, 50, 1, 329], [398, 241, 50, 1, 248], [331, 107, 64, 454, 369], [6, 433, 16, 1]]


### **Word Embedding Represntation -**

In [54]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [55]:
import numpy as np

In [56]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 107 121 454 406]
 [  0   0   0   0 107 121 454 414]
 [  0   0   0   0 107 306 454 153]
 [  0   0   0 398 241  50   1 329]
 [  0   0   0 398 241  50   1 248]
 [  0   0   0 331 107  64 454 369]
 [  0   0   0   0   6 433  16   1]]


In [57]:
# My Feature Representaion / Feature Dimension  -
dim=10

In [58]:
model=Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=10, input_shape=(sent_length,))) #here , our sent_length is 8.
model.compile('adam','mse')

In [59]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 8, 10)          │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [60]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 107, 121, 454, 406], dtype=int32)

In [62]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step


array([[[-0.02436569, -0.00830988, -0.03174757, -0.03310137,
         -0.04263657, -0.03117504, -0.01567652, -0.01551683,
          0.0294816 , -0.04905849],
        [-0.02436569, -0.00830988, -0.03174757, -0.03310137,
         -0.04263657, -0.03117504, -0.01567652, -0.01551683,
          0.0294816 , -0.04905849],
        [-0.02436569, -0.00830988, -0.03174757, -0.03310137,
         -0.04263657, -0.03117504, -0.01567652, -0.01551683,
          0.0294816 , -0.04905849],
        [-0.02436569, -0.00830988, -0.03174757, -0.03310137,
         -0.04263657, -0.03117504, -0.01567652, -0.01551683,
          0.0294816 , -0.04905849],
        [-0.01232406, -0.04827582, -0.02143249,  0.04350771,
         -0.00048665, -0.04587773,  0.00368009, -0.01593035,
         -0.02196168,  0.00068749],
        [-0.00516843, -0.02322774, -0.0447909 ,  0.00600774,
          0.02775047, -0.0013914 ,  0.03993021,  0.04831767,
         -0.04160901,  0.02656429],
        [-0.02714366,  0.03188625,  0.01647497, -0.0

In [63]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
[[[-0.02436569 -0.00830988 -0.03174757 -0.03310137 -0.04263657
   -0.03117504 -0.01567652 -0.01551683  0.0294816  -0.04905849]
  [-0.02436569 -0.00830988 -0.03174757 -0.03310137 -0.04263657
   -0.03117504 -0.01567652 -0.01551683  0.0294816  -0.04905849]
  [-0.02436569 -0.00830988 -0.03174757 -0.03310137 -0.04263657
   -0.03117504 -0.01567652 -0.01551683  0.0294816  -0.04905849]
  [-0.02436569 -0.00830988 -0.03174757 -0.03310137 -0.04263657
   -0.03117504 -0.01567652 -0.01551683  0.0294816  -0.04905849]
  [-0.01232406 -0.04827582 -0.02143249  0.04350771 -0.00048665
   -0.04587773  0.00368009 -0.01593035 -0.02196168  0.00068749]
  [-0.00516843 -0.02322774 -0.0447909   0.00600774  0.02775047
   -0.0013914   0.03993021  0.04831767 -0.04160901  0.02656429]
  [-0.02714366  0.03188625  0.01647497 -0.01183044  0.01173041
    0.02554491  0.04880222  0.03909484 -0.03959774  0.01481033]
  [ 0.04931173  0.04914891 -0.00220631 -0.04625076  0.03353614
    0.0122